services:
  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mailnetwork
    depends_on:
      - mailhog
    
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - mailnetwork
    
networks:
  mailnetwork: